In [7]:
import numpy as np

scalar = 3.7

array = np.array([1,3,5,6,7,9])


print("\nSine:")
print(np.sin(array))

print("\nCoine:")
print(np.cos(array))

print("\nTangent:")
print(np.tan(array))


Sine:
[ 0.84147098  0.14112001 -0.95892427 -0.2794155   0.6569866   0.41211849]

Coine:
[ 0.54030231 -0.9899925   0.28366219  0.96017029  0.75390225 -0.91113026]

Tangent:
[ 1.55740772 -0.14254654 -3.38051501 -0.29100619  0.87144798 -0.45231566]


In [8]:
matrix = np.array([[2,4], [5, 6]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

exp_values = np.exp(matrix)
log_values = np.log(matrix)

abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

rem_values = np.remainder(matrix, 2)

round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[2 4]
 [5 6]]

sin:
 [[ 0.90929743 -0.7568025 ]
 [-0.95892427 -0.2794155 ]]

cos:
 [[-0.41614684 -0.65364362]
 [ 0.28366219  0.96017029]]

tan:
 [[-2.18503986  1.15782128]
 [-3.38051501 -0.29100619]]

asine:
 [[0.33983691 0.72972766]
 [0.98511078 1.57079633]]

acosine:
 [[1.23095942 0.84106867]
 [0.58568554 0.        ]]

atangent:
 [[1.10714872 1.32581766]
 [1.37340077 1.40564765]]

exp:
 [[  7.3890561   54.59815003]
 [148.4131591  403.42879349]]

log (natural):
 [[0.69314718 1.38629436]
 [1.60943791 1.79175947]]

abs:
 [[2 4]
 [5 6]]

sqrt:
 [[1.41421356 2.        ]
 [2.23606798 2.44948974]]

rem (remainder when divided by 2):
 [[0 0]
 [1 0]]

round:
 [[2 4]
 [5 6]]

floor:
 [[2. 4.]
 [5. 6.]]

ceil:
 [[2. 4.]
 [5. 6.]]


In [12]:
matrix = np.array([[2,3], [4,5],[6,7]])

sin_values = np.sin(matrix)
cos_values = np.cos(matrix)
tan_values = np.tan(matrix)
asin_values = np.arcsin(np.clip(matrix / np.max(matrix), -1, 1))
acos_values = np.arccos(np.clip(matrix / np.max(matrix), -1, 1))
atan_values = np.arctan(matrix)

exp_values = np.exp(matrix)
log_values = np.log(matrix)

abs_values = np.abs(matrix)
sqrt_values = np.sqrt(matrix)

rem_values = np.remainder(matrix, 2)

round_values = np.round(matrix)
floor_values = np.floor(matrix)
ceil_values = np.ceil(matrix)

print("Matrix:\n", matrix)
print("\nsin:\n", sin_values)
print("\ncos:\n", cos_values)
print("\ntan:\n", tan_values)
print("\nasine:\n", asin_values)
print("\nacosine:\n", acos_values)
print("\natangent:\n", atan_values)
print("\nexp:\n", exp_values)
print("\nlog (natural):\n", log_values)
print("\nabs:\n", abs_values)
print("\nsqrt:\n", sqrt_values)
print("\nrem (remainder when divided by 2):\n", rem_values)
print("\nround:\n", round_values)
print("\nfloor:\n", floor_values)
print("\nceil:\n", ceil_values)

Matrix:
 [[2 3]
 [4 5]
 [6 7]]

sin:
 [[ 0.90929743  0.14112001]
 [-0.7568025  -0.95892427]
 [-0.2794155   0.6569866 ]]

cos:
 [[-0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219]
 [ 0.96017029  0.75390225]]

tan:
 [[-2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501]
 [-0.29100619  0.87144798]]

asine:
 [[0.2897517  0.44291104]
 [0.60824558 0.79560295]
 [1.0296968  1.57079633]]

acosine:
 [[1.28104463 1.12788528]
 [0.96255075 0.77519337]
 [0.54109953 0.        ]]

atangent:
 [[1.10714872 1.24904577]
 [1.32581766 1.37340077]
 [1.40564765 1.42889927]]

exp:
 [[   7.3890561    20.08553692]
 [  54.59815003  148.4131591 ]
 [ 403.42879349 1096.63315843]]

log (natural):
 [[0.69314718 1.09861229]
 [1.38629436 1.60943791]
 [1.79175947 1.94591015]]

abs:
 [[2 3]
 [4 5]
 [6 7]]

sqrt:
 [[1.41421356 1.73205081]
 [2.         2.23606798]
 [2.44948974 2.64575131]]

rem (remainder when divided by 2):
 [[0 1]
 [0 1]
 [0 1]]

round:
 [[2 3]
 [4 5]
 [6 7]]

floor:
 [[2. 3.]
 [4. 5.]
 [6. 7.]]

ceil:
 

In [10]:
matrix = np.array([[2,4,6], [1, 3, 5]])

max_value = np.max(matrix)
max_index = np.argmax(matrix)

min_value = np.min(matrix)
min_index = np.argmin(matrix)

matrix_shape = matrix.shape

sorted_matrix_rows = np.sort(matrix, axis=1)
sorted_matrix_cols = np.sort(matrix, axis=0)


sum_values = np.sum(matrix)

prod_values = np.prod(matrix)

median_value = np.median(matrix)

mean_value = np.mean(matrix)

std_dev = np.std(matrix)

print("Matrix:\n", matrix)
print("Max value:", max_value, "at index", max_index)
print("Min value:", min_value, "at index", min_index)
print("Shape of matrix:", matrix_shape)
print("Sorted matrix (rows):\n", sorted_matrix_rows)
print("Sorted matrix (cols):\n", sorted_matrix_cols)
print("Sum of elements:", sum_values)
print("Product of elements:", prod_values)
print("Median value:", median_value)
print("Mean value:", mean_value)
print("Standard deviation:", std_dev)


Matrix:
 [[2 4 6]
 [1 3 5]]
Max value: 6 at index 2
Min value: 1 at index 3
Shape of matrix: (2, 3)
Sorted matrix (rows):
 [[2 4 6]
 [1 3 5]]
Sorted matrix (cols):
 [[1 3 5]
 [2 4 6]]
Sum of elements: 21
Product of elements: 720
Median value: 3.5
Mean value: 3.5
Standard deviation: 1.707825127659933
